[package]
name = "zerunet"
version = "0.1.0"
authors = ["Ansho Rei <anshorei@zeroid.bit>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
serde = { version = "*", features = ["derive"] }
signatory = { version = "0.13", features = ["ecdsa"] }
signatory-ring = "0.13"
bitcoin = "*"
ripemd160 = "*"
secp256k1 = { version = "0.15.5", features = ["recovery", "rand"] }
base64 = "*"
rand = { version = "0.6.5", features = ["rand_os"] }
sha2 = "*"
hex = "*"
basex-rs = "0.1.1"
json_filter_sorted = { path = "json_filter_sorted" }
log = "0.4"
pretty_env_logger = "0.3"
# rusqlite = "*"
actix = "*"
actix-web = "*"
actix-files = "*"
actix-web-actors = "*"
i2p = { git = "https://github.com/i2p/i2p-rs" }
reqwest = "*"
env_logger = "0.6.2"
pulldown-cmark = "*"
futures = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }
